### ISSUE TITLE
had no valid text and no meta data was parsed

### ISSUE THREAD

**Issue by imfurkaann** [h2oai/h2ogpt#1133]
def test_readme_example(local_server):
    # self-contained example used for readme, to be copied to README_CLIENT.md if changed, setting local_server = True at first
    import os
    # The grclient.py file can be copied from h2ogpt repo and used with local gradio_client for example use
    from gradio_utils.grclient import GradioClient

    if local_server:
        client = GradioClient("http://0.0.0.0:7860")
    else:
        h2ogpt_key = os.getenv('H2OGPT_KEY') or os.getenv('H2OGPT_H2OGPT_KEY')
        if h2ogpt_key is None:
            return
        # if you have API key for public instance:
        client = GradioClient("https://gpt.h2o.ai", h2ogpt_key=h2ogpt_key)

    # LLM
    print(client.question("Who are you?"))

    url = "https://cdn.openai.com/papers/whisper.pdf"

    # Q/A
    print(client.query("What is whisper?", url=url))
    # summarization (map_reduce over all pages if top_k_docs=-1)
    print(client.summarize("What is whisper?", url=url, top_k_docs=3))
    # extraction (map per page)
    print(client.extract("Give bullet for all key points", url=url, top_k_docs=3))
test_readme_example(local_server=True)

Failed to ingest https://cdn.openai.com/papers/whisper.pdf due to Traceback (most recent call last):
  File "C:\Users\MSI\Documents\7_PDF-GPT\h2ogpt\src\gpt_langchain.py", line 2862, in path_to_doc1
    res = file_to_doc(file,
  File "C:\Users\MSI\Documents\7_PDF-GPT\h2ogpt\src\gpt_langchain.py", line 2681, in file_to_doc
    raise ValueError("%s had no valid text and no meta data was parsed: %s" % (file, str(e)))
ValueError: urls_downloaded\__945178b2-2_whisper.pdf had no valid text and no meta data was parsed: None

**Comment by pseudotensor** [comment]
Probably something incomplete with your installation.

**Comment by nylocx** [comment]
I have the same using the docker container docx for example is working fine but all PDFs return the no valid text error. Any ideas on that?

**Comment by pseudotensor** [comment]
@nylocx I can only guess that there is then something odd with the PDFs.  Can you share any of them?

**Comment by nylocx** [comment]
Sure, I guess that it should not be the pdf document as it worked on h2ogpt.ai. But here is the PDF:
[A Sample PDF-komprimiert.pdf](https://github.com/h2oai/h2ogpt/files/13562708/A.Sample.PDF-komprimiert.pdf)

And here my docker compose file:
```
services:
  h2ogpt:
    image: ${H2OGPT_RUNTIME}
    restart: always
    shm_size: '2gb'
    ports:
      - '${H2OGPT_PORT}:7860'
    volumes:
      - cache:/workspace/.cache
      - save:/workspace/save
    command: ${H2OGPT_ARGS}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]

volumes:
  cache:
  save:

```

and my vars:
```
H2OGPT_PORT=7860
H2OGPT_RUNTIME=gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0
H2OGPT_BASE_MODEL=HuggingFaceH4/zephyr-7b-beta
H2OGPT_ARGS="/workspace/generate.py --base_model=${H2OGPT_BASE_MODEL} --use_safetensors=True --prompt_type=zephyr --save_dir=/workspace/save/ --use_gpu_id=False --score_model=None --max_max_new_tokens=2048 --max_new_tokens=1024"
```
