### ISSUE TITLE
minimum requirement for running h2ogpt docker : CUDA out of memory

### ISSUE THREAD

**Issue by ctxwing** [h2oai/h2ogpt#1353]
Q1) any minimum requirement for running h2ogpt docker ? 
      should GPU have at least N GB ? 
      
  -  got " torch.cuda.OutOfMemoryError: CUDA out of memory."
   - at now , using  GeForce RTX 2070 (8GB) as shown below : 
   - tried to set "PYTORCH_CUDA_ALLOC_CONF" but seem result in vain.
   - ive  tested  CPU version and it work good except performance.
   
Q2) any workaround to cope with  CUDA OOM ?

thank so much in advance. 
----------
   in docker-compose.yml as below: 
   ### docker-compose.yml 
```
version: '3'

services:
  h2ogpt:
    image: ${H2OGPT_RUNTIME} 
    container_name: h2ogpt_ctx
    restart: always
    shm_size: "2gb" 
    environment:
    #   - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb=128
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256 # Replace with your chosen value
      # Only add CUDA_LAUNCH_BLOCKING=1 as a last resort after careful consideration
    ports:
      - '${H2OGPT_PORT}:7860'
    volumes:
      #- cache:/workspace/.cache
      #- save:/workspace/save
 
      - ../workspace/.cache:/workspace/.cache
      - ../workspace/save:/workspace/save
      - ../workspace/user_path:/workspace/user_path  
      - ../workspace/db_dir_UserData:/workspace/db_dir_UserData
      - ../workspace/users:/workspace/users
      - ../workspace/db_nonusers:/workspace/db_nonusers
      - ../workspace/llamacpp_path:/workspace/llamacpp_path
      - ../workspace/h2ogpt_auth:/workspace/h2ogpt_auth
    #command: ${H2OGPT_CPU_ARGS}

    command: |
      /workspace/generate.py 
      --base_model=${H2OGPT_BASE_MODEL} 
      --use_safetensors=True 
      --prompt_type=llama2 
      --save_dir=/workspace/save/ 
      --use_gpu_id=False 
      --score_model=None 
      --max_max_new_tokens=2048 
      --max_new_tokens=1024
      --load_half=True 
      --h2ocolors=False
    # --load_half=True
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1 # all # This reserves GPU with index 0
            capabilities: [gpu]
```

### GPU : 8 GB
*-display
                description: VGA compatible controller
                product: TU106 [GeForce RTX 2070]
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:01:00.0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: vga_controller bus_master cap_list rom
                configuration: driver=nvidia latency=0

### nvidia-smi
```
nvidia-smi
Sun Feb  4 16:47:48 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2070        Off | 00000000:01:00.0 Off |                  N/A |
|  0%   39C    P8               6W / 175W |      1MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

```

### docker log
```
$docker compose up -d 
h2ogpt-240203  | Using Model h2oai/h2ogpt-4096-llama2-7b-chat
h2ogpt-240203  | fatal: not a git repository (or any of the parent directories): .git
h2ogpt-240203  | load INSTRUCTOR_Transformer
h2ogpt-240203  | max_seq_length  512
h2ogpt-240203  | Starting get_model: h2oai/h2ogpt-4096-llama2-7b-chat 
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
h2ogpt-240203  | Starting get_model: h2oai/h2ogpt-4096-llama2-7b-chat 
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
h2ogpt-240203  | Starting get_model: h2oai/h2ogpt-4096-llama2-7b-chat 
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
h2ogpt-240203  | Starting get_model: h2oai/h2ogpt-4096-llama2-7b-chat 
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
h2ogpt-240203  | Traceback (most recent call last):
h2ogpt-240203  |   File "/workspace/generate.py", line 16, in <module>
h2ogpt-240203  |     entrypoint_main()
h2ogpt-240203  |   File "/workspace/generate.py", line 12, in entrypoint_main
h2ogpt-240203  |     H2O_Fire(main)
h2ogpt-240203  |   File "/workspace/src/utils.py", line 65, in H2O_Fire
h2ogpt-240203  |     fire.Fire(component=component, command=args)
h2ogpt-240203  |   File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
h2ogpt-240203  |     component_trace = _Fire(component, args, parsed_flag_args, context, name)
h2ogpt-240203  |   File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
h2ogpt-240203  |     component, remaining_args = _CallAndUpdateTrace(
h2ogpt-240203  |   File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
h2ogpt-240203  |     component = fn(*varargs, **kwargs)
h2ogpt-240203  |   File "/workspace/src/gen.py", line 1977, in main
h2ogpt-240203  |     model0, tokenizer0, device = get_model_retry(reward_type=False,
h2ogpt-240203  |   File "/workspace/src/gen.py", line 2305, in get_model_retry
h2ogpt-240203  |     model1, tokenizer1, device1 = get_model(**kwargs)
h2ogpt-240203  |   File "/workspace/src/gen.py", line 2729, in get_model
h2ogpt-240203  |     return get_hf_model(load_8bit=load_8bit,
h2ogpt-240203  |   File "/workspace/src/gen.py", line 2933, in get_hf_model
h2ogpt-240203  |     model = model_loader(
h2ogpt-240203  |   File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
h2ogpt-240203  |     return model_class.from_pretrained(
h2ogpt-240203  |   File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3850, in from_pretrained
h2ogpt-240203  |     ) = cls._load_pretrained_model(
h2ogpt-240203  |   File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4259, in _load_pretrained_model
h2ogpt-240203  |     state_dict = load_state_dict(shard_file)
h2ogpt-240203  |   File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 513, in load_state_dict
h2ogpt-240203  |     return safe_load_file(checkpoint_file)
h2ogpt-240203  |   File "/h2ogpt_conda/lib/python3.10/site-packages/safetensors/torch.py", line 310, in load_file
h2ogpt-240203  |     result[k] = f.get_tensor(k)
h2ogpt-240203  |   File "/h2ogpt_conda/lib/python3.10/site-packages/torch/utils/_device.py", line 77, in __torch_function__
h2ogpt-240203  |     return func(*args, **kwargs)
h2ogpt-240203  | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacty of 7.79 GiB of which 24.50 MiB is free. Process 249900 has 7.76 GiB memory in use. Of the allocated memory 7.61 GiB is allocated by PyTorch, and 43.20 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
