### ISSUE TITLE
umbrella podSecurityContext null values are always overwritten by sub-chart default values

### ISSUE THREAD

**Issue by robinliubin** [h2oai/h2ogpt#1616]
when install on openshift using umbrella chart.
umbrella can NOT nullify podSecurityContext, if set to null, it will be override by h2oGPT default values.

details in: https://github.com/h2oai/platform-charts/issues/260

need to set below values to empty, not default 1000:
https://github.com/h2oai/h2ogpt/blob/6824d21afc8633dc678e0f4dcdd0e450827faf91/helm/h2ogpt-chart/values.yaml#L69-L73
to 
```yaml
  podSecurityContext:
    runAsNonRoot: true
    runAsUser:
    runAsGroup:
    fsGroup:

```
