### ISSUE TITLE
GPU Installation

### ISSUE THREAD

**Issue by jaysunl** [h2oai/h2ogpt#1624]
May I possibly have specific instructions as for the GPU installation of the tool? I have followed the installation but it still says no GPU detected. I have the following GPU on my system:  NVIDIA Corporation GA102GL [A10G] (rev a1) and my nvcc --version output is 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

And tried to install Pytorch CUDA. But when I run
import torch
print(torch.cuda.is_available())

it still says False and when I try to run a model, it still says no GPU detected. Any guidance would be appreciated.

**Comment by pseudotensor** [comment]
It's a good start that you checked that torch condition.  We only really support cuda 12.1 and above at this point, so maybe there's some issue with the installation because you have old cuda toolkit.  It's easy to follow our instructions for installing the cuda toolkit 12.1, but you'll need drivers that are also compatible.

**Comment by jaysunl** [comment]
Ok I was actually able to follow the GPU version of PyTorch. But the launching of the actual interface takes forever. I am running this command:
python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6_9b --load_8bit=True --langchain_mode=UserData --user_path=/some/path

but the output gets stuck at this:
soundfile, librosa, and wavio not installed, disabling STT
soundfile, librosa, and wavio not installed, disabling TTS
Using Model h2oai/h2ogpt-oig-oasst1-512-6_9b

with nothing after it. It has been like that for at least an hour. Any tips?

**Comment by pseudotensor** [comment]
I recommend not using h2oai/h2ogpt-oig-oasst1-512-6_9b as a model, but instead a GGUF model at first like `https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF`.  Also, ensure to -pass `--verbose=True` to get more info.

```
python generate.py --base_model=llama --model_path_llama=https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct.Q5_K_M.gguf?download=true --tokenizer_base_model=meta-llama/Meta-Llama-3-8B-Instruct --max_seq_len=8192 --verbose=True
```

**Comment by jaysunl** [comment]
Sorry, I'm getting a Python: no match error when I enter this command and I copied it exactly as is.

**Comment by pseudotensor** [comment]
Can you find the PID of the process and when it gets stuck in a separate terminal do `kill -s SIGUSR1 PID` ?  and share the full traceback.

**Comment by jaysunl** [comment]
It says SIGUSR1: Unknown signal; kill -l lists signals.

**Comment by pseudotensor** [comment]
What platform are you using?  linux, windows, mac?

**Comment by jaysunl** [comment]
Linux

**Comment by pseudotensor** [comment]
Ok that's very odd, not sure about that.  Normal PC w/ Linux has that signal, you must have something else special.

Try downloading the FILE separately and place in the llamacpp_path folder, then start h2oGPT with `--base_model=llama --llama_cpp_path=FILE` .

**Comment by pseudotensor** [comment]
So during getting or initializing the embedding model, which should be fairly trivial.  It's not clear, and really hard to debug without SIGUSR1.

**Comment by jaysunl** [comment]
Sorry for the late reply. I just tried the Docker version and encountered an out of space error running docker build -t h2ogpt .


--> 39936edc8bac
Step 15/25 : RUN chmod -R a+rwx /workspace
---> Running in 216f25a14b33
write /workspace/llamacpp_path/zephyr-7b-beta.Q5_K_M.gguf: no space left on device



How much space is this expected to use?

**Comment by pseudotensor** [comment]
When you build a docker image, make sure the local path is clean.  E.g. I recommend a separate clone of the repo and be in there.

**Comment by jaysunl** [comment]
Ok I have managed to build the container. I ran this example on the README:

mkdir -p ~/.cache
mkdir -p ~/save
mkdir -p ~/user_path
mkdir -p ~/db_dir_UserData
mkdir -p ~/users
mkdir -p ~/db_nonusers
mkdir -p ~/llamacpp_path
mkdir -p ~/h2ogpt_auth
echo '["key1","key2"]' > ~/h2ogpt_auth/h2ogpt_api_keys.json
export GRADIO_SERVER_PORT=7860
export OPENAI_SERVER_PORT=5000
docker run \
       --gpus all \
       --runtime=nvidia \
       --shm-size=2g \
       -p $GRADIO_SERVER_PORT:$GRADIO_SERVER_PORT \
       -p $OPENAI_SERVER_PORT:$OPENAI_SERVER_PORT \
       --rm --init \
       --network host \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u `id -u`:`id -g` \
       -v "${HOME}"/.cache:/workspace/.cache \
       -v "${HOME}"/save:/workspace/save \
       -v "${HOME}"/user_path:/workspace/user_path \
       -v "${HOME}"/db_dir_UserData:/workspace/db_dir_UserData \
       -v "${HOME}"/users:/workspace/users \
       -v "${HOME}"/db_nonusers:/workspace/db_nonusers \
       -v "${HOME}"/llamacpp_path:/workspace/llamacpp_path \
       -v "${HOME}"/h2ogpt_auth:/workspace/h2ogpt_auth \
       -e GRADIO_SERVER_PORT=$GRADIO_SERVER_PORT \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:0.2.0 /workspace/generate.py \
          --base_model=HuggingFaceH4/zephyr-7b-beta \
          --use_safetensors=True \
          --prompt_type=zephyr \
          --save_dir='/workspace/save/' \
          --auth_filename='/workspace/h2ogpt_auth/auth.json'
          --h2ogpt_api_keys='/workspace/h2ogpt_auth/h2ogpt_api_keys.json'
          --use_gpu_id=False \
          --user_path=/workspace/user_path \
          --langchain_mode="LLM" \
          --langchain_modes="['UserData', 'LLM']" \
          --score_model=None \
          --max_max_new_tokens=2048 \
          --max_new_tokens=1024 \
          --use_auth_token="${HUGGING_FACE_HUB_TOKEN}" \
          --openai_port=$OPENAI_SERVER_PORT

But seems to be hanging after this output:
WARNING: Published ports are discarded when using host network mode
Using Model huggingfaceh4/zephyr-7b-beta
fatal: not a git repository (or any of the parent directories): .git

I am running this in the h2ogpt directory.

**Comment by pseudotensor** [comment]
Yes, if you made multiple collections, but want each to be served separately, then you can make them with make_db, then later launch separate h2oGPT for each, using CLI options like used here: https://github.com/h2oai/h2ogpt/blob/main/docs/README_LangChain.md#multiple-embeddings-and-sources

You can use TEI server to share the embeddings if you want to save on GPU and get better speed.  I share in FAQ how gpt.h2o.ai is setup using TEI server: https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#text-embedding-inference-server

**Comment by jaysunl** [comment]
Ok sounds good thanks! I am also receiving this error 

``` 
h2ogpt_1  | WARNING:matplotlib:Matplotlib created a temporary cache directory at /tmp/matplotlib-l50c0tvu because the default path (/workspace/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
h2ogpt_1  | There was a problem when trying to write in your cache folder (/workspace/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
h2ogpt_1  | Using Model huggingfaceh4/zephyr-7b-beta
h2ogpt_1  | fatal: not a git repository (or any of the parent directories): .git
h2ogpt_1  | Traceback (most recent call last):
h2ogpt_1  |   File "/workspace/generate.py", line 20, in <module>
h2ogpt_1  |     entrypoint_main()
h2ogpt_1  |   File "/workspace/generate.py", line 16, in entrypoint_main
h2ogpt_1  |     H2O_Fire(main)
h2ogpt_1  |   File "/workspace/src/utils.py", line 72, in H2O_Fire
h2ogpt_1  |     fire.Fire(component=component, command=args)
h2ogpt_1  |   File "/h2ogpt_conda/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
h2ogpt_1  |     component_trace = _Fire(component, args, parsed_flag_args, context, name)
h2ogpt_1  |   File "/h2ogpt_conda/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
h2ogpt_1  |     component, remaining_args = _CallAndUpdateTrace(
h2ogpt_1  |   File "/h2ogpt_conda/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
h2ogpt_1  |     component = fn(*varargs, **kwargs)
h2ogpt_1  |   File "/workspace/src/gen.py", line 1886, in main
h2ogpt_1  |     model=get_embedding(use_openai_embedding, hf_embedding_model=hf_embedding_model,
h2ogpt_1  |   File "/workspace/src/gpt_langchain.py", line 544, in get_embedding
h2ogpt_1  |     embedding = HuggingFaceEmbeddings(model_name=hf_embedding_model, model_kwargs=model_kwargs)
h2ogpt_1  |   File "/h2ogpt_conda/envs/h2ogpt/lib/python3.10/site-packages/langchain_community/embeddings/huggingface.py", line 72, in __init__
h2ogpt_1  |     self.client = sentence_transformers.SentenceTransformer(
h2ogpt_1  |   File "/h2ogpt_conda/envs/h2ogpt/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__
h2ogpt_1  |     snapshot_download(model_name_or_path,
h2ogpt_1  |   File "/h2ogpt_conda/envs/h2ogpt/lib/python3.10/site-packages/sentence_transformers/util.py", line 476, in snapshot_download
h2ogpt_1  |     os.makedirs(nested_dirname, exist_ok=True)
h2ogpt_1  |   File "/h2ogpt_conda/envs/h2ogpt/lib/python3.10/os.py", line 215, in makedirs
h2ogpt_1  |     makedirs(head, exist_ok=exist_ok)
h2ogpt_1  |   File "/h2ogpt_conda/envs/h2ogpt/lib/python3.10/os.py", line 215, in makedirs
h2ogpt_1  |     makedirs(head, exist_ok=exist_ok)
h2ogpt_1  |   File "/h2ogpt_conda/envs/h2ogpt/lib/python3.10/os.py", line 225, in makedirs
h2ogpt_1  |     mkdir(name, mode)
h2ogpt_1  | PermissionError: [Errno 13] Permission denied: '/workspace/.cache/torch'
```

after running `docker-compose up -d --build`. My docker-compose.yml looks like this
```
version: '3'

services:
  h2ogpt:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    shm_size: '2gb'
    ports:
      - '${H2OGPT_PORT}:7860'
    volumes:
      #- cache:/workspace/.cache
      #- save:/workspace/save
      - ../workspace/.cache:/workspace/.cache
      - ../workspace/save:/workspace/save
      - ../workspace/user_path:/workspace/user_path
      - ../workspace/db_dir_UserData:/workspace/db_dir_UserData
      - ../workspace/users:/workspace/users
      - ../workspace/db_nonusers:/workspace/db_nonusers
      - ../workspace/llamacpp_path:/workspace/llamacpp_path
      - ../workspace/h2ogpt_auth:/workspace/h2ogpt_auth
    command: |
      /workspace/generate.py
      --base_model=HuggingFaceH4/zephyr-7b-beta
      --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2
      --score_model=None
      --use_gpu_id=0
 --langchain_mode='UserData'
      --langchain_modes=['UserData2']
      --enable_tts=False
      --enable_stt=False
      --enable_transcriptions=False
      --max_seq_len=2048
      --load_4bit=True
      --share=True
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

volumes:
  cache:
  save:
```

Any workarounds?
