### ISSUE TITLE
Docker Image Permission Issues

### ISSUE THREAD

**Issue by ffalkenberg** [h2oai/h2ogpt#651]
Hello maintainers,

I've encountered a problem when trying to deploy the `h2ogpt` Docker image on a Kubernetes/OC cluster. The deployment fails due to a `Permission denied` error. I believe the root cause is the way the Docker image is set up.

**Issue Details:**

1. Python is installed and run from the `/root` directory. This is problematic as many Kubernetes environments restrict running containers as root for security reasons.
2. The Docker image does not seem to be set up in a manner that's conducive for professional deployments, especially in environments that have strict security policies.

**Deployment Configuration:**

We are using the following `deployment.yaml`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2ogpt-deployment
  labels:
    app: h2ogpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h2ogpt
  template:
    metadata:
      labels:
        app: h2ogpt
    spec:
      containers:
      - name: h2ogpt-container
        image: gcr.io/vorvan/h2oai/h2ogpt-runtime:latest
        ports:
        - containerPort: 7860
        env:
        - name: HOME
          value: /workspace/
        volumeMounts:
        - name: cache-volume
          mountPath: /workspace/.cache
        - name: save-volume
          mountPath: /workspace/save
        command:
          - tail
          - '-f'
          - /dev/null
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: cache-pvc
      - name: save-volume
        persistentVolumeClaim:
          claimName: save-pvc
```

**Temporary Solution:**

As a quick fix, we built an additional layer on top of the existing image:

```Dockerfile
FROM gcr.io/vorvan/h2oai/h2ogpt-runtime:latest

RUN chgrp -R 0 /root && \
    chmod -R g=u /root

RUN chgrp -R 0 /workspace && \
    chmod -R g=u /workspace
```

However, this is not a sustainable long-term solution.

**Request:**

I kindly request that the Docker image be restructured to avoid such permission issues, especially when deploying in environments like Kubernetes. Ideally, the image should not rely on the `/root` directory for operations and should be set up in a way that respects common security practices.

Thank you for your attention to this matter.

Dockerfile: [Link](https://github.com/h2oai/h2ogpt/blob/main/Dockerfile)
Dockerimage: [Link](https://console.cloud.google.com/gcr/images/vorvan/global/h2oai/h2ogpt-runtime)

**Comment by pseudotensor** [comment]
Thanks, we will take a look at it ASAP

**Comment by pseudotensor** [comment]
Please take a look @achraf-mer and @ChathurindaRanasinghe

**Comment by parkeraddison** [comment]
Over at https://github.com/h2oai/h2o-llmstudio/blob/main/Dockerfile they're using an "llmstudio" user in the container. Perhaps it would help to do the same here?

**Comment by ffalkenberg** [comment]
I don't think such a user would help, this is from llmstudio container:

- The user is `llmstudio`:

  ```
  llmstudio@h2o-llmstudio1:/workspace$ whoami
  llmstudio
  ```

- Directory permissions under `/workspace`:

  ```
  llmstudio@h2o-llmstudio1:/workspace$ ls -la
  total 328
  drwxr-xr-x 1 root root    598 Aug  2 22:31 .
  drwxr-xr-x 1 root root    240 Aug 12 05:41 ..
  ...
  [Trimmed for brevity]
  ...
  -rw-r--r-- 1 root root   5576 Aug  2 22:23 train_wave.py 
  ```

**Comment by ffalkenberg** [comment]
However user + changing dir + changing owner could work. Something like this:

```Dockerfile
# ... (existing Dockerfile content up to the point of Miniconda installation)

# Create a new user 'llmstudio'
RUN useradd -m llmstudio

# Install Miniconda into /usr/bin/miniconda3
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Linux-x86_64.sh && \
    bash ./Miniconda3-py310_23.1.0-1-Linux-x86_64.sh -b -p /usr/bin/miniconda3

# Update PATH environment variable
ENV PATH="/usr/bin/miniconda3/bin:${PATH}"

# Change the ownership of the directories to 'llmstudio'
RUN chown -R llmstudio:llmstudio /workspace && \
    chown -R llmstudio:llmstudio /usr/bin/miniconda3

# Set the working directory to /workspace
WORKDIR /workspace

# Switch to 'llmstudio'
USER llmstudio

# ... (rest of your Dockerfile content)
```

By making these changes, you ensure that the container runs as the user `llmstudio` and that this user has the necessary permissions to execute the application and its dependencies from the `/workspace` directory.

**Comment by parkeraddison** [comment]
Nice. I'd recommend setting chmod a+rwX so that we avoid permissions errors when the docker container is run as a existing host user, too!

**Comment by lamw** [comment]
@ffalkenberg Can you share your manifest files on getting this to work on k8s?

**Comment by ffalkenberg** [comment]
Hello @lamw,

Certainly! Below is an example of the Kubernetes manifest I used to deploy the h2ogpt :

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: save-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2ogpt-deployment
  labels:
    app: h2ogpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h2ogpt
  template:
    metadata:
      labels:
        app: h2ogpt
    spec:
      containers:
      - name: h2ogpt-container
        image: gcr.io/vorvan/h2oai/h2ogpt-runtime:latest
        ports:
        - containerPort: 7860
        env:
        # proxy address, adjust or remove as necessary
        - name: HTTPS_PROXY
          value: http://your-proxy-address:8080
        - name: HOME
          value: /workspace/
        volumeMounts:
        - name: cache-volume
          mountPath: /workspace/.cache
        - name: save-volume
          mountPath: /workspace/save
        # This command is used to keep the pod running. Replace with h2ogpt command when needed.
        command:
          - tail
          - '-f'
          - /dev/null
        resources:
          limits:
            cpu: '4'
            memory: 25G
            # The NVIDIA MIG configuration specifies how GPU resources should be allocated
            # This depends on the Kubernetes cluster environment and can be skipped if not relevant.
            nvidia.com/mig-7g.40gb: '1'
          requests:
            cpu: '4'
            memory: 25G
            nvidia.com/mig-7g.40gb: '1'
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: cache-pvc
      - name: save-volume
        persistentVolumeClaim:
          claimName: save-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: h2ogpt-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
  selector:
    app: h2ogpt
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: 'true'
  labels:
    app: h2ogpt-route
  name: h2ogpt-route
spec:
  to:
    kind: Service
    name: h2ogpt-service
    weight: 100
  port:
    targetPort: 7860
  wildcardPolicy: None

```

You might need to adjust it based on your specific requirements and environment.

Additionally, there's now a Helm chart available as part of the repository. It can greatly simplify the deployment process on Kubernetes. I'd highly recommend checking it out if you haven't already.

I hope this helps! Let me know if you have any further questions or need additional details.
